//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberFees
    {
        public int memberFeeId { get; set; }
        public int memberLoanId { get; set; }
        public int memberId { get; set; }
        public int payrollNumber { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public System.DateTime recordDate { get; set; }
        public decimal amountFee { get; set; }
        public decimal previousBalance { get; set; }
        public decimal currentBalance { get; set; }
        public int feeBalance { get; set; }
        public int memberFeeStatusId { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
    
        public virtual memberFeeStatus memberFeeStatus { get; set; }
        public virtual memberLoans memberLoans { get; set; }
    }
}
