//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberFeeStatus
    {
        public memberFeeStatus()
        {
            this.memberFees = new HashSet<memberFees>();
        }
    
        public int memberFeeStatusId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<memberFees> memberFees { get; set; }
    }
}
