//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberLoans
    {
        public memberLoans()
        {
            this.memberFees = new HashSet<memberFees>();
        }
    
        public int memberLoanId { get; set; }
        public int memberId { get; set; }
        public int loanTypeId { get; set; }
        public int memberLoanStatusId { get; set; }
        public Nullable<System.DateTime> appDate { get; set; }
        public Nullable<System.DateTime> aprDate { get; set; }
        public string Notes { get; set; }
    
        public virtual loanTypes loanTypes { get; set; }
        public virtual ICollection<memberFees> memberFees { get; set; }
        public virtual memberLoansStatus memberLoansStatus { get; set; }
        public virtual members members { get; set; }
    }
}
