//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class members
    {
        public members()
        {
            this.memberChilds = new HashSet<memberChilds>();
            this.memberLoans = new HashSet<memberLoans>();
        }
    
        public int memberId { get; set; }
        public string documentId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int maritalStatusId { get; set; }
        public System.DateTime birthdate { get; set; }
        public string phoneNumber { get; set; }
        public string cellNumber { get; set; }
        public string address { get; set; }
        public int officeId { get; set; }
        public System.DateTime dischargedDate { get; set; }
        public int paymentTypeId { get; set; }
        public bool active { get; set; }
        public string fullname { get { return firstName + " " + lastName; } }
    
        public virtual ICollection<memberChilds> memberChilds { get; set; }
        public virtual ICollection<memberLoans> memberLoans { get; set; }
        public virtual memberMaritalStatus memberMaritalStatus { get; set; }
        public virtual memberPaymentTypes memberPaymentTypes { get; set; }
        public virtual offices offices { get; set; }
    }
}
