//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberChilds
    {
        public int memberChildId { get; set; }
        public int memberId { get; set; }
        public string firtName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthdate { get; set; }
    
        public virtual members members { get; set; }
    }
}
