//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF.net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XenosENEntities : DbContext
    {
        public XenosENEntities()
            : base("name=XenosENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<loanTypes> loanTypes { get; set; }
        public DbSet<memberChilds> memberChilds { get; set; }
        public DbSet<memberFees> memberFees { get; set; }
        public DbSet<memberFeeStatus> memberFeeStatus { get; set; }
        public DbSet<memberLoans> memberLoans { get; set; }
        public DbSet<memberLoansStatus> memberLoansStatus { get; set; }
        public DbSet<memberMaritalStatus> memberMaritalStatus { get; set; }
        public DbSet<memberPaymentTypes> memberPaymentTypes { get; set; }
        public DbSet<members> members { get; set; }
        public DbSet<offices> offices { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<View_PendingsPayments> View_PendingsPayments { get; set; }
    }
}
