//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PendingsPayments
    {
        public int Operacion { get; set; }
        public string NombreFull { get; set; }
        public string nombreCredito { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public Nullable<decimal> montoCuota { get; set; }
        public Nullable<int> MontoSaldoActual { get; set; }
        public Nullable<int> CuotasHechas { get; set; }
        public Nullable<int> SaldoCuotas { get; set; }
    }
}
